// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Messages/proto/service_login.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace P4TLB.MasterServer {
  public static partial class Authentication
  {
    static readonly string __ServiceName = "P4TLB.MasterServer.Authentication";

    static readonly grpc::Marshaller<global::P4TLB.MasterServer.UserLoginRequest> __Marshaller_P4TLB_MasterServer_UserLoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::P4TLB.MasterServer.UserLoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::P4TLB.MasterServer.UserLoginResponse> __Marshaller_P4TLB_MasterServer_UserLoginResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::P4TLB.MasterServer.UserLoginResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::P4TLB.MasterServer.UserSignUpRequest> __Marshaller_P4TLB_MasterServer_UserSignUpRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::P4TLB.MasterServer.UserSignUpRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::P4TLB.MasterServer.UserSignUpResponse> __Marshaller_P4TLB_MasterServer_UserSignUpResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::P4TLB.MasterServer.UserSignUpResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::P4TLB.MasterServer.UserLoginRequest, global::P4TLB.MasterServer.UserLoginResponse> __Method_SendUserLogin = new grpc::Method<global::P4TLB.MasterServer.UserLoginRequest, global::P4TLB.MasterServer.UserLoginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendUserLogin",
        __Marshaller_P4TLB_MasterServer_UserLoginRequest,
        __Marshaller_P4TLB_MasterServer_UserLoginResponse);

    static readonly grpc::Method<global::P4TLB.MasterServer.UserSignUpRequest, global::P4TLB.MasterServer.UserSignUpResponse> __Method_SendUserSignUp = new grpc::Method<global::P4TLB.MasterServer.UserSignUpRequest, global::P4TLB.MasterServer.UserSignUpResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendUserSignUp",
        __Marshaller_P4TLB_MasterServer_UserSignUpRequest,
        __Marshaller_P4TLB_MasterServer_UserSignUpResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::P4TLB.MasterServer.ServiceLoginReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Authentication</summary>
    [grpc::BindServiceMethod(typeof(Authentication), "BindService")]
    public abstract partial class AuthenticationBase
    {
      public virtual global::System.Threading.Tasks.Task<global::P4TLB.MasterServer.UserLoginResponse> SendUserLogin(global::P4TLB.MasterServer.UserLoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::P4TLB.MasterServer.UserSignUpResponse> SendUserSignUp(global::P4TLB.MasterServer.UserSignUpRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Authentication</summary>
    public partial class AuthenticationClient : grpc::ClientBase<AuthenticationClient>
    {
      /// <summary>Creates a new client for Authentication</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuthenticationClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Authentication that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuthenticationClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuthenticationClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuthenticationClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::P4TLB.MasterServer.UserLoginResponse SendUserLogin(global::P4TLB.MasterServer.UserLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendUserLogin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::P4TLB.MasterServer.UserLoginResponse SendUserLogin(global::P4TLB.MasterServer.UserLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendUserLogin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::P4TLB.MasterServer.UserLoginResponse> SendUserLoginAsync(global::P4TLB.MasterServer.UserLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendUserLoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::P4TLB.MasterServer.UserLoginResponse> SendUserLoginAsync(global::P4TLB.MasterServer.UserLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendUserLogin, null, options, request);
      }
      public virtual global::P4TLB.MasterServer.UserSignUpResponse SendUserSignUp(global::P4TLB.MasterServer.UserSignUpRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendUserSignUp(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::P4TLB.MasterServer.UserSignUpResponse SendUserSignUp(global::P4TLB.MasterServer.UserSignUpRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendUserSignUp, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::P4TLB.MasterServer.UserSignUpResponse> SendUserSignUpAsync(global::P4TLB.MasterServer.UserSignUpRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendUserSignUpAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::P4TLB.MasterServer.UserSignUpResponse> SendUserSignUpAsync(global::P4TLB.MasterServer.UserSignUpRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendUserSignUp, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuthenticationClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthenticationClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthenticationBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendUserLogin, serviceImpl.SendUserLogin)
          .AddMethod(__Method_SendUserSignUp, serviceImpl.SendUserSignUp).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthenticationBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendUserLogin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::P4TLB.MasterServer.UserLoginRequest, global::P4TLB.MasterServer.UserLoginResponse>(serviceImpl.SendUserLogin));
      serviceBinder.AddMethod(__Method_SendUserSignUp, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::P4TLB.MasterServer.UserSignUpRequest, global::P4TLB.MasterServer.UserSignUpResponse>(serviceImpl.SendUserSignUp));
    }

  }
}
#endregion
